HA_PREFIX = "homeassistant"
HA_SWITCH = "switch"
HA_LIGHT = "light"
HA_CLIMATE = "climate"
HA_SENSOR = "sensor"
HA_FAN = "fan"

BRIDGE_TOPIC_PREFIX = "wallpad/bridge"
TOPIC_BRIDGE_LOG_LEVEL = f"{BRIDGE_TOPIC_PREFIX}/config/log_level"
TOPIC_BRIDGE_RESTART = f"{BRIDGE_TOPIC_PREFIX}/config/restart"
TOPIC_BRIDGE_REMOVE = f"{BRIDGE_TOPIC_PREFIX}/config/remove"
TOPIC_BRIDGE_SCAN = f"{BRIDGE_TOPIC_PREFIX}/config/scan"
TOPIC_BRIDGE_PACKET = f"{BRIDGE_TOPIC_PREFIX}/config/packet"
TOPIC_BRIDGE_CHECKSUM = f"{BRIDGE_TOPIC_PREFIX}/config/check_sum"
